#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.42000
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyAmnesty.Resource", IsApplication=true)]

namespace MyAmnesty
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int splash = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070015
			public const int button100 = 2131165205;
			
			// aapt resource value: 0x7f070010
			public const int button10euro = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int button20 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int button30 = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int button40 = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int button50 = 2131165204;
			
			// aapt resource value: 0x7f070016
			public const int buttonAnder = 2131165206;
			
			// aapt resource value: 0x7f07000e
			public const int buttonDoneer = 2131165198;
			
			// aapt resource value: 0x7f070003
			public const int editTextAchternaam = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int editTextAdres = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int editTextEmail = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int editTextGemeente = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int editTextNummer = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int editTextRekening = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int editTextValidatie = 2131165197;
			
			// aapt resource value: 0x7f070001
			public const int editTextVoornaam = 2131165185;
			
			// aapt resource value: 0x7f07000f
			public const int textView1 = 2131165199;
			
			// aapt resource value: 0x7f070000
			public const int textView2 = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int textView3 = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int textView4 = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int textView5 = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int textView6 = 2131165195;
			
			// aapt resource value: 0x7f070009
			public const int textView7 = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Formulier = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
